accompanied	ac:DERI|PREFIX compani:ROOT|ROOT::NOMINAL ed:INFL|INFL::CONJ|SUFFIX
accompaniment	ac:DERI|PREFIX compani:ROOT|ROOT::NOMINAL ment:DERI|DERI::NOUN|SUFFIX
acknowledging	ac:DERI|PREFIX knowledg:ROOT|ROOT::NOMINAL ing:INFL|INFL::CONJ|SUFFIX
acquisition	acquis:ROOT|ROOT::VERBAL ition:DERI|DERI::NOUN|SUFFIX
acquisitions'	acquis:ROOT|ROOT::VERBAL ition:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
acupuncture	acupuncture:ROOT|ROOT::NOMINAL
acupuncture's	acupuncture:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
adjudged	ad:DERI|PREFIX judg:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
advantageously	advant:ROOT|ROOT::VERBAL age:DERI|DERI::NOUN|SUFFIX ous:DERI|DERI::ADJ|SUFFIX ly:DERI|DERI::ADV|SUFFIX
afire	a:DERI|PREFIX fire:ROOT|ROOT::NOMINAL
afire	a:DERI|PREFIX fire:ROOT|ROOT::NOMINAL
ageing	age:ROOT|ROOT::NOMINAL ing:INFL|INFL::CONJ|SUFFIX
ageing	ageing:ROOT|ROOT::VERBAL
agelessness	age:ROOT|ROOT::NOMINAL less:DERI|DERI::ADJ|SUFFIX ness:DERI|DERI::NOUN|SUFFIX
airlocks	air:ROOT|ROOT::NOMINAL lock:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
airspeed	air:ROOT|ROOT::NOMINAL speed:ROOT|ROOT::VERBAL
algeria	algeria:ROOT|ROOT::NOMINAL
algerians	algeri:ROOT|ROOT::NOMINAL an:DERI|DERI::ADJ|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
alter	alter:ROOT|ROOT::VERBAL
alters	alter:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
alumni's	alumni:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
alumnus'	alumnus:ROOT|ROOT::NOMINAL ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
antimatter	anti:DERI|PREFIX matter:ROOT|ROOT::NOMINAL
anyhow	any:ROOT how:ROOT
anyplace	any:ROOT place:ROOT|ROOT::NOMINAL
apartment's	a:DERI|PREFIX part:ROOT|ROOT::NOMINAL ment:DERI|DERI::NOUN|SUFFIX 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
archaism	archa:ROOT|ROOT::ADJECTIVAL ism:DERI|DERI::NOUN|SUFFIX
archaisms	archa:ROOT|ROOT::ADJECTIVAL ism:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
archdeacons	arch:DERI|PREFIX deacon:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
archetypal	archetyp:ROOT|ROOT::NOMINAL al:DERI|DERI::ADJ|SUFFIX
archetype	archetype:ROOT|ROOT::NOMINAL
archimandrite's	archimandrite:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
arrangements	arrange:ROOT|ROOT::VERBAL ment:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
astronomers'	astr:DERI|PREFIX onom:DERI|DERI::NOUN|SUFFIX er:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
aureola	aureola:ROOT|ROOT::NOMINAL
backpedal	back:ROOT pedal:ROOT|ROOT::NOMINAL
badly-off	bad:ROOT|ROOT::ADJECTIVAL ly:DERI|DERI::ADV|SUFFIX -:UNK off:ROOT
badness	bad:ROOT|ROOT::ADJECTIVAL ness:DERI|DERI::NOUN|SUFFIX
ballets	ballet:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
ballets'	ballet:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
bane	bane:ROOT|ROOT::NOMINAL
bane's	bane:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
batiste	batiste:ROOT|ROOT::NOMINAL
batiste's	batiste:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
batsmen	bat:ROOT|ROOT::NOMINAL s:UNK men:ROOT|ROOT::NOMINAL
beachhead	beach:ROOT|ROOT::NOMINAL head:ROOT|ROOT::NOMINAL
beachwear	beach:ROOT|ROOT::NOMINAL wear:ROOT|ROOT::VERBAL
bedsore	bed:ROOT|ROOT::NOMINAL sore:ROOT|ROOT::ADJECTIVAL
bequeath	bequeath:ROOT|ROOT::VERBAL
bequeathed	bequeath:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
berthing	berth:ROOT|ROOT::NOMINAL ing:INFL|INFL::CONJ|SUFFIX
berths	berth:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
berths	berth:ROOT|ROOT::NOMINAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
best-looking	best:ROOT|ROOT::ADJECTIVAL -:UNK looking:ROOT|ROOT::VERBAL
bestir	be:DERI|PREFIX stir:ROOT|ROOT::VERBAL
bethel	bethel:ROOT|ROOT::NOMINAL
bethel's	bethel:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
betrayal	betray:ROOT|ROOT::VERBAL al:DERI|DERI::ADJ|SUFFIX
betrays	betray:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
billies	billi:ROOT|ROOT::NOMINAL es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
billies'	billi:ROOT|ROOT::NOMINAL es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
bipartite	bi:DERI|PREFIX part:ROOT|ROOT::NOMINAL ite:DERI|DERI::NOUN|SUFFIX
blinder's	blind:ROOT|ROOT::ADJECTIVAL er:DERI|DERI::NOUN|SUFFIX 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
bluster's	bluster:ROOT|ROOT::VERBAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
blusterer	bluster:ROOT|ROOT::VERBAL er:DERI|DERI::NOUN|SUFFIX
bookshop's	book:ROOT|ROOT::NOMINAL shop:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
bootlace	boot:ROOT|ROOT::NOMINAL lace:ROOT|ROOT::NOMINAL
boundaries	bound:ROOT|ROOT::VERBAL ari:DERI|DERI::ADJ|SUFFIX es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
bounteously	bount:ROOT|ROOT::NOMINAL eous:DERI|DERI::NOUN|SUFFIX ly:DERI|DERI::ADV|SUFFIX
bountiful	bounti:ROOT|ROOT::NOMINAL ful:DERI|DERI::ADJ|SUFFIX
bread-and-butter	bread-and-butter:ROOT|ROOT::ADJECTIVAL
bribery	brib:ROOT|ROOT::VERBAL ery:DERI|DERI::NOUN|SUFFIX
bribes'	bribe:ROOT|ROOT::VERBAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
brushes	brush:ROOT|ROOT::NOMINAL es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
brushes	brush:ROOT|ROOT::NOMINAL es:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
brushes'	brush:ROOT|ROOT::NOMINAL es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
brushwood	brush:ROOT|ROOT::NOMINAL wood:ROOT|ROOT::NOMINAL
buckled	buckl:ROOT|ROOT::NOMINAL ed:INFL|INFL::CONJ|SUFFIX
buckles'	buckle:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
bypassing	by:ROOT pass:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
cacao	cacao:ROOT|ROOT::NOMINAL
cankered	canker:ROOT|ROOT::NOMINAL ed:INFL|INFL::CONJ|SUFFIX
cankers	canker:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
cankers	canker:ROOT|ROOT::NOMINAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
capitulating	capitulat:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
capsicum	capsicum:ROOT|ROOT::NOMINAL
capsicums	capsicum:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
carded	card:ROOT|ROOT::NOMINAL ed:INFL|INFL::CONJ|SUFFIX
cashiers	cash:ROOT|ROOT::NOMINAL ier:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
cashiers	cashier:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
caucuses	caucus:ROOT|ROOT::NOMINAL es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
caucuses	caucus:ROOT|ROOT::NOMINAL es:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
cauliflower's	cauliflower:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
cauliflowers	cauliflower:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
cent	cent:UNK
cent	cent:ROOT|ROOT::NOMINAL
centenarians	centenari:ROOT|ROOT::NOMINAL an:DERI|DERI::ADJ|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
centralized	centr:ROOT|ROOT::NOMINAL al:DERI|DERI::ADJ|SUFFIX iz:DERI|DERI::VERB|SUFFIX ed:INFL|INFL::CONJ|SUFFIX
centrals	centr:ROOT|ROOT::NOMINAL al:DERI|DERI::ADJ|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
cents'	cent:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
challenged	challeng:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
challenger's	challeng:ROOT|ROOT::VERBAL er:DERI|DERI::NOUN|SUFFIX 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
chart's	chart:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
cheeks'	cheek:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
cheeky	cheek:ROOT|ROOT::NOMINAL y:DERI|DERI::ADJ|SUFFIX
chlorinates	chlorin:ROOT|ROOT::NOMINAL ate:DERI|DERI::VERB|SUFFIX s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
chlorine	chlorine:ROOT|ROOT::NOMINAL
chocolates	chocolate:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
choice	choice:ROOT|ROOT::NOMINAL
choice	choice:ROOT|ROOT::NOMINAL
choicest	choic:ROOT|ROOT::NOMINAL est:INFL|INFL::NOUNADJ|SUFFIX
choked	chok:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
chokes	choke:ROOT|ROOT::VERBAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
chokes	choke:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
chronic	chronic:ROOT|ROOT::ADJECTIVAL
chronically	chronic:ROOT|ROOT::ADJECTIVAL ally:DERI|DERI::ADV|SUFFIX
classless	class:ROOT|ROOT::NOMINAL less:DERI|DERI::ADJ|SUFFIX
clean-living	clean:ROOT|ROOT::ADJECTIVAL -:UNK living:ROOT|ROOT::VERBAL
cliched	clich:ROOT|ROOT::NOMINAL ed:DERI|DERI::ADJ|SUFFIX
cliches	cliche:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
clotheshorse	clothes:ROOT|ROOT::NOMINAL horse:ROOT|ROOT::NOMINAL
coach	coach:ROOT|ROOT::NOMINAL
coach	coach:ROOT|ROOT::NOMINAL
coddle	coddle:ROOT|ROOT::VERBAL
coffee	coffee:ROOT|ROOT::NOMINAL
coffees	coffee:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
cognac	cognac:ROOT|ROOT::NOMINAL
cognac's	cognac:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
coinage	coin:ROOT|ROOT::NOMINAL age:DERI|DERI::NOUN|SUFFIX
coinages	coin:ROOT|ROOT::NOMINAL age:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
collectivization	collect:ROOT|ROOT::VERBAL iv:DERI|DERI::ADJ|SUFFIX iz:DERI|DERI::VERB|SUFFIX ation:DERI|DERI::NOUN|SUFFIX
combust	combust:ROOT|ROOT::VERBAL
combustible	combust:ROOT|ROOT::VERBAL ible:DERI|DERI::ADJ|SUFFIX
combustible	combust:ROOT|ROOT::VERBAL ible:DERI|DERI::ADJ|SUFFIX
conclusive	conclus:ROOT|ROOT::VERBAL ive:DERI|DERI::ADJ|SUFFIX
concurrences	concurr:ROOT|ROOT::VERBAL ence:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
concurs	concur:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
consul's	consul:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
continental's	contin:ROOT|ROOT::VERBAL ent:DERI|DERI::ADJ|DERI::NOUN|SUFFIX al:DERI|DERI::ADJ|SUFFIX 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
copilot	co:DERI|PREFIX pilot:ROOT|ROOT::NOMINAL
coreligionists	co:DERI|PREFIX religion:ROOT|ROOT::NOMINAL ist:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
coterie	coterie:ROOT|ROOT::NOMINAL
coteries	coterie:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
countrified	countr:ROOT|ROOT::NOMINAL ifi:DERI|DERI::VERB|SUFFIX ed:DERI|DERI::ADJ|SUFFIX
cover	cover:ROOT|ROOT::VERBAL
cover	cover:ROOT|ROOT::VERBAL
coxswain	coxswain:ROOT|ROOT::NOMINAL
coxswain	coxswain:ROOT|ROOT::NOMINAL
coxswain's	coxswain:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
crikey	crikey:UNK
cross-country	cross:DERI|PREFIX -:UNK country:ROOT|ROOT::NOMINAL
cross-talk	cross:DERI|PREFIX -:UNK talk:ROOT|ROOT::VERBAL
crudities	crud:ROOT|ROOT::ADJECTIVAL iti:DERI|DERI::NOUN|SUFFIX es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
curatorship	curator:ROOT|ROOT::NOMINAL ship:DERI|DERI::NOUN|SUFFIX
curatorships	curator:ROOT|ROOT::NOMINAL ship:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
cusp	cusp:ROOT|ROOT::NOMINAL
cusps	cusp:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
dangle	dangle:ROOT|ROOT::VERBAL
dangles	dangle:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
deacon's	deacon:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
defections	defect:ROOT|ROOT::VERBAL ion:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
defectors	defect:ROOT|ROOT::VERBAL or:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
defrosters	de:DERI|PREFIX frost:ROOT|ROOT::NOMINAL er:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
denuding	de:DERI|PREFIX nud:ROOT|ROOT::ADJECTIVAL ing:INFL|INFL::CONJ|SUFFIX
derogate	derogate:ROOT|ROOT::VERBAL
derogating	derogat:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
describe	describe:ROOT|ROOT::VERBAL
dices	dice:ROOT|ROOT::NOMINAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
diciest	dic:ROOT|ROOT::NOMINAL i:DERI|DERI::ADJ|SUFFIX est:INFL|INFL::NOUNADJ|SUFFIX
dictatorial	dictat:ROOT|ROOT::VERBAL or:DERI|DERI::NOUN|SUFFIX ial:DERI|DERI::ADJ|SUFFIX
dictators'	dictat:ROOT|ROOT::VERBAL or:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
dinner-service	dinn:ROOT|ROOT::VERBAL er:DERI|DERI::NOUN|SUFFIX -:UNK serv:ROOT|ROOT::VERBAL ice:DERI|DERI::NOUN|SUFFIX
disagrees	dis:DERI|PREFIX agree:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
discipline	discipline:ROOT|ROOT::VERBAL
discipline	discipline:ROOT|ROOT::VERBAL
disciplined	disciplin:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
discovery's	dis:DERI|PREFIX cov:ROOT|ROOT::VERBAL ery:DERI|DERI::NOUN|SUFFIX 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
displace	dis:DERI|PREFIX place:ROOT|ROOT::NOMINAL
disproportionately	dis:DERI|PREFIX proportion:ROOT|ROOT::VERBAL ate:DERI|DERI::VERB|SUFFIX ly:DERI|DERI::ADV|SUFFIX
disregarded	dis:DERI|PREFIX regard:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
disregarding	dis:DERI|PREFIX regard:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
disservice	dis:DERI|PREFIX serv:ROOT|ROOT::VERBAL ice:DERI|DERI::NOUN|SUFFIX
dissimilar	dis:DERI|PREFIX similar:ROOT|ROOT::ADJECTIVAL
distasteful	dis:DERI|PREFIX taste:ROOT|ROOT::VERBAL ful:DERI|DERI::ADJ|SUFFIX
distasteful	dis:DERI|PREFIX tasteful:ROOT|ROOT::ADJECTIVAL
distiller	distill:ROOT|ROOT::VERBAL er:DERI|DERI::NOUN|SUFFIX
distilling	distill:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
do-gooders	do:ROOT|ROOT::VERBAL -:UNK good:ROOT|ROOT::ADJECTIVAL er:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
donates	donate:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
donation	donat:ROOT|ROOT::VERBAL ion:DERI|DERI::NOUN|SUFFIX
double-basses	double:ROOT|ROOT::ADJECTIVAL -:UNK bass:ROOT|ROOT::NOMINAL es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
doubled	doubl:ROOT|ROOT::ADJECTIVAL ed:INFL|INFL::CONJ|SUFFIX
dreamier	dream:ROOT|ROOT::VERBAL i:DERI|DERI::ADJ|SUFFIX er:INFL|INFL::NOUNADJ|SUFFIX
duvet's	duvet:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
duvets	duvet:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
earthbound	earth:ROOT|ROOT::NOMINAL bound:ROOT|ROOT::VERBAL
earthiness'	earth:ROOT|ROOT::NOMINAL i:DERI|DERI::ADJ|SUFFIX ness:DERI|DERI::NOUN|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
eating-place	eating:ROOT|ROOT::VERBAL -:UNK place:ROOT|ROOT::NOMINAL
ecologist	ec:DERI|PREFIX olog:DERI|DERI::NOUN|SUFFIX ist:DERI|DERI::NOUN|SUFFIX
elder	elder:ROOT|ROOT::NOMINAL
elder	elder:ROOT|ROOT::ADJECTIVAL
elderberries	elder:ROOT|ROOT::NOMINAL berri:ROOT|ROOT::NOMINAL es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
embalmer	em:DERI|PREFIX balm:ROOT|ROOT::NOMINAL er:DERI|DERI::NOUN|SUFFIX
embeds	em:DERI|PREFIX bed:ROOT|ROOT::NOMINAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
embellishing	embellish:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
entreating	entreat:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
entreaty	entreat:ROOT|ROOT::VERBAL y:DERI|DERI::ADJ|SUFFIX
expletive	expletive:ROOT|ROOT::NOMINAL
expletives	expletive:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
explorations	explor:ROOT|ROOT::VERBAL ation:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
exploratory	explor:ROOT|ROOT::VERBAL at:DERI|DERI::NOUN|SUFFIX ory:DERI|DERI::ADJ|DERI::NOUN|SUFFIX
extemporaneously	ex:DERI|PREFIX temporan:ROOT|ROOT::ADJECTIVAL eous:DERI|DERI::NOUN|SUFFIX ly:DERI|DERI::ADV|SUFFIX
extensions	extens:ROOT|ROOT::VERBAL ion:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
extensiveness	extens:ROOT|ROOT::VERBAL ive:DERI|DERI::ADJ|SUFFIX ness:DERI|DERI::NOUN|SUFFIX
facet	facet:ROOT|ROOT::NOMINAL
facet's	facet:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
falsehoods'	false:ROOT|ROOT::ADJECTIVAL hood:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
fame	fame:ROOT|ROOT::NOMINAL
faults	fault:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
faults	fault:ROOT|ROOT::NOMINAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
fauna	fauna:ROOT|ROOT::NOMINAL
felicitous	felicit:ROOT|ROOT::NOMINAL ous:DERI|DERI::ADJ|SUFFIX
fickle	fickle:ROOT|ROOT::ADJECTIVAL
fickleness	fickle:ROOT|ROOT::ADJECTIVAL ness:DERI|DERI::NOUN|SUFFIX
fin	fin:ROOT|ROOT::NOMINAL
fins	fin:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
fistula	fistula:ROOT|ROOT::NOMINAL
fistulas	fistula:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
flabbergasting	flabbergast:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
flabbergasts	flabbergast:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
flat-footed	flat:ROOT|ROOT::ADJECTIVAL -:UNK foot:ROOT|ROOT::NOMINAL ed:DERI|DERI::ADJ|SUFFIX
flattops	flat:ROOT|ROOT::ADJECTIVAL top:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
flowchart	flow:ROOT|ROOT::VERBAL chart:ROOT|ROOT::NOMINAL
folk-dance	folk:ROOT|ROOT::NOMINAL -:UNK dance:ROOT|ROOT::VERBAL
folklore	folk:ROOT|ROOT::NOMINAL lore:ROOT|ROOT::NOMINAL
follow-on	follow:ROOT|ROOT::VERBAL -:UNK on:ROOT
foot-faulting	foot:ROOT|ROOT::NOMINAL -:UNK fault:ROOT|ROOT::NOMINAL ing:INFL|INFL::CONJ|SUFFIX
footage	foot:ROOT|ROOT::NOMINAL age:DERI|DERI::NOUN|SUFFIX
forbidden	forbidden:ROOT|ROOT::VERBAL
forbidden	forbidden:ROOT|ROOT::VERBAL
forbidding	forbidd:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
forbidding	forbidding:ROOT|ROOT::VERBAL
ford's	ford:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
fords	ford:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
fords	ford:ROOT|ROOT::NOMINAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
foresaw	fore:DERI|PREFIX saw:ROOT|ROOT::VERBAL
foresees	fore:DERI|PREFIX see:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
fortnight	for:ROOT t:UNK night:ROOT|ROOT::NOMINAL
fortnights	for:ROOT t:UNK night:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
forward	forward:ROOT|ROOT::ADJECTIVAL
forward	forward:ROOT
forward	forward:ROOT
forward	forward:ROOT
forward-looking	forward:ROOT -:UNK looking:ROOT|ROOT::VERBAL
forwarded	forward:ROOT ed:INFL|INFL::CONJ|SUFFIX
fountain's	fountain:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
fountains'	fountain:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
fourpenny	four:ROOT penny:ROOT|ROOT::NOMINAL
freaking	freak:ROOT|ROOT::NOMINAL ing:INFL|INFL::CONJ|SUFFIX
freaks'	freak:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
fresher	fresh:ROOT|ROOT::ADJECTIVAL er:INFL|INFL::NOUNADJ|SUFFIX
fresher	fresh:ROOT|ROOT::ADJECTIVAL er:DERI|DERI::NOUN|SUFFIX
funded	fund:ROOT|ROOT::NOMINAL ed:INFL|INFL::CONJ|SUFFIX
funds	fund:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
funds	fund:ROOT|ROOT::NOMINAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
funds	funds:ROOT|ROOT::NOMINAL
funds'	fund:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
funds'	funds:ROOT|ROOT::NOMINAL ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
furred	furr:ROOT|ROOT::NOMINAL ed:INFL|INFL::CONJ|SUFFIX
furrier	furr:ROOT|ROOT::NOMINAL i:DERI|DERI::ADJ|SUFFIX er:INFL|INFL::NOUNADJ|SUFFIX
furrier	furr:ROOT|ROOT::NOMINAL ier:DERI|DERI::NOUN|SUFFIX
furrier's	furr:ROOT|ROOT::NOMINAL ier:DERI|DERI::NOUN|SUFFIX 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
gaiter's	gaiter:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
gaiters'	gaiter:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
gawp	gawp:ROOT|ROOT::VERBAL
gawping	gawp:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
gibbon	gibbon:ROOT|ROOT::NOMINAL
gibbons'	gibbon:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
gibraltarian	gibraltar:ROOT|ROOT::NOMINAL ian:DERI|DERI::NOUN|SUFFIX
gibraltarian	gibraltar:ROOT|ROOT::NOMINAL ian:DERI|DERI::NOUN|SUFFIX
gibraltarians	gibraltar:ROOT|ROOT::NOMINAL ian:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
gipsies	gipsi:ROOT|ROOT::NOMINAL es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
gipsies'	gipsi:ROOT|ROOT::NOMINAL es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
gladdens	gladd:ROOT|ROOT::ADJECTIVAL en:DERI|DERI::ADJ|SUFFIX s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
gladly	glad:ROOT|ROOT::ADJECTIVAL ly:DERI|DERI::ADV|SUFFIX
gladness	glad:ROOT|ROOT::ADJECTIVAL ness:DERI|DERI::NOUN|SUFFIX
goo	goo:ROOT|ROOT::NOMINAL
goo's	goo:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
graduates'	graduate:ROOT|ROOT::VERBAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
graspingly	grasping:ROOT|ROOT::VERBAL ly:DERI|DERI::ADV|SUFFIX
grocer's	grocer:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
grocers	grocer:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
guardians	guard:ROOT|ROOT::NOMINAL ian:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
gumboot	gum:ROOT|ROOT::NOMINAL boot:ROOT|ROOT::NOMINAL
gumshoe's	gum:ROOT|ROOT::NOMINAL shoe:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
halt	halt:ROOT|ROOT::NOMINAL
halt	halt:ROOT|ROOT::NOMINAL
halt's	halt:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
ham	ham:ROOT|ROOT::NOMINAL
ham	ham:ROOT|ROOT::NOMINAL
hammed	hamm:ROOT|ROOT::NOMINAL ed:INFL|INFL::CONJ|SUFFIX
hamstrings	ham:ROOT|ROOT::NOMINAL string:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
hamstrings	ham:ROOT|ROOT::NOMINAL string:ROOT|ROOT::NOMINAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
hardest-hearted	hardest:ROOT|ROOT::ADJECTIVAL -:UNK heart:ROOT|ROOT::NOMINAL ed:DERI|DERI::ADJ|SUFFIX
hardware's	hard:ROOT|ROOT::ADJECTIVAL ware:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
hatcheries	hatch:ROOT|ROOT::VERBAL eri:DERI|DERI::NOUN|SUFFIX es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
have-nots	have:ROOT|ROOT::VERBAL -:UNK not:ROOT s:UNK
having	hav:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
heeding	heed:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
heedlessly	heed:ROOT|ROOT::VERBAL less:DERI|DERI::ADJ|SUFFIX ly:DERI|DERI::ADV|SUFFIX
holograph	holograph:ROOT|ROOT::NOMINAL
holographs	holograph:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
honduras	honduras:ROOT|ROOT::NOMINAL
honduras'	honduras:ROOT|ROOT::NOMINAL ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
horseshoe	horse:ROOT|ROOT::NOMINAL shoe:ROOT|ROOT::NOMINAL
hotfoot	hot:ROOT|ROOT::ADJECTIVAL foot:ROOT|ROOT::NOMINAL
hotfoot	hot:ROOT|ROOT::ADJECTIVAL foot:ROOT|ROOT::NOMINAL
hothouse	hot:ROOT|ROOT::ADJECTIVAL house:ROOT|ROOT::NOMINAL
houses	house:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
houses	house:ROOT|ROOT::NOMINAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
hurricane's	hurricane:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
hurricanes'	hurricane:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
illness's	ill:ROOT|ROOT::ADJECTIVAL ness:DERI|DERI::NOUN|SUFFIX 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
importer	import:ROOT|ROOT::VERBAL er:DERI|DERI::NOUN|SUFFIX
importers'	import:ROOT|ROOT::VERBAL er:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
imports	import:ROOT|ROOT::VERBAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
imports	import:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
inanities	inan:ROOT|ROOT::ADJECTIVAL iti:DERI|DERI::NOUN|SUFFIX es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
inanity	inan:ROOT|ROOT::ADJECTIVAL ity:DERI|DERI::NOUN|SUFFIX
indescribable	in:DERI|PREFIX describ:ROOT|ROOT::VERBAL able:DERI|DERI::ADJ|SUFFIX
industrial	industri:ROOT|ROOT::NOMINAL al:DERI|DERI::ADJ|SUFFIX
industry	industry:ROOT|ROOT::NOMINAL
infamies	infami:ROOT|ROOT::NOMINAL es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
infamous	in:DERI|PREFIX fam:ROOT|ROOT::NOMINAL ous:DERI|DERI::ADJ|SUFFIX
infamous	infam:ROOT|ROOT::NOMINAL ous:DERI|DERI::ADJ|SUFFIX
infelicitous	in:DERI|PREFIX felicit:ROOT|ROOT::NOMINAL ous:DERI|DERI::ADJ|SUFFIX
influencing	influenc:ROOT|ROOT::NOMINAL ing:INFL|INFL::CONJ|SUFFIX
influentially	influent:ROOT|ROOT::NOMINAL ial:DERI|DERI::ADJ|SUFFIX ly:DERI|DERI::ADV|SUFFIX
insensitivity	in:DERI|PREFIX sensitiv:ROOT|ROOT::ADJECTIVAL ity:DERI|DERI::NOUN|SUFFIX
intensely	in:DERI|PREFIX tense:ROOT|ROOT::ADJECTIVAL ly:DERI|DERI::ADV|SUFFIX
internationalists'	inter:DERI|PREFIX nation:ROOT|ROOT::NOMINAL al:DERI|DERI::ADJ|SUFFIX ist:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
ironic	iron:ROOT|ROOT::NOMINAL ic:DERI|DERI::ADJ|SUFFIX
ironies	ironi:ROOT|ROOT::NOMINAL es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
isolate	isolate:ROOT|ROOT::VERBAL
isolationism	isolat:ROOT|ROOT::VERBAL ion:DERI|DERI::NOUN|SUFFIX ism:DERI|DERI::NOUN|SUFFIX
jazzes	jazz:ROOT|ROOT::NOMINAL es:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
jazzily	jazz:ROOT|ROOT::NOMINAL i:DERI|DERI::ADJ|SUFFIX ly:DERI|DERI::ADV|SUFFIX
jesuitical	jesuit:ROOT|ROOT::NOMINAL ical:DERI|DERI::ADJ|SUFFIX
jollies	jolli:ROOT|ROOT::ADJECTIVAL es:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
jollities	joll:ROOT|ROOT::ADJECTIVAL iti:DERI|DERI::NOUN|SUFFIX es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
judgement	judge:ROOT|ROOT::VERBAL ment:DERI|DERI::NOUN|SUFFIX
juveniles	juvenile:ROOT|ROOT::ADJECTIVAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
knee-high	knee:ROOT|ROOT::NOMINAL -:UNK high:ROOT|ROOT::ADJECTIVAL
knee-high	knee:ROOT|ROOT::NOMINAL -:UNK high:ROOT|ROOT::ADJECTIVAL
kneecaps	knee:ROOT|ROOT::NOMINAL cap:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
kneecaps	knee:ROOT|ROOT::NOMINAL cap:ROOT|ROOT::NOMINAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
kneeing	knee:ROOT|ROOT::NOMINAL ing:INFL|INFL::CONJ|SUFFIX
knitwear's	knit:ROOT|ROOT::VERBAL wear:ROOT|ROOT::VERBAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
laps	lap:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
laps	lap:ROOT|ROOT::VERBAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
laps	lap:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
launch	launch:ROOT|ROOT::NOMINAL
launch	launch:ROOT|ROOT::VERBAL
launch	launch:ROOT|ROOT::VERBAL
launches'	launch:ROOT|ROOT::NOMINAL es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
launching	launch:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
layabouts	lay:ROOT|ROOT::VERBAL about:ROOT s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
layers'	lay:ROOT|ROOT::VERBAL er:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
ledge	ledge:ROOT|ROOT::NOMINAL
ledges	ledge:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
left's	left:ROOT|ROOT::ADJECTIVAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
left-hander	left:ROOT|ROOT::ADJECTIVAL -:UNK hand:ROOT|ROOT::NOMINAL er:DERI|DERI::NOUN|SUFFIX
limitation's	limit:ROOT|ROOT::NOMINAL ation:DERI|DERI::NOUN|SUFFIX 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
livelihoods	live:ROOT|ROOT::ADJECTIVAL li:DERI|DERI::ADV|SUFFIX hood:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
livestock's	live:ROOT|ROOT::ADJECTIVAL stock:ROOT|ROOT::VERBAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
living-space	living:ROOT|ROOT::VERBAL -:UNK space:ROOT|ROOT::NOMINAL
looking-glasses	looking:ROOT|ROOT::VERBAL -:UNK glass:ROOT|ROOT::NOMINAL es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
lord	lord:UNK
lord	lord:ROOT|ROOT::NOMINAL
lord	lord:ROOT|ROOT::NOMINAL
lord	lord:ROOT|ROOT::NOMINAL
lore's	lore:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
lurid	lurid:ROOT|ROOT::ADJECTIVAL
luridness	lurid:ROOT|ROOT::ADJECTIVAL ness:DERI|DERI::NOUN|SUFFIX
lustful	lust:ROOT|ROOT::NOMINAL ful:DERI|DERI::ADJ|SUFFIX
lustiness	lust:ROOT|ROOT::NOMINAL i:DERI|DERI::ADJ|SUFFIX ness:DERI|DERI::NOUN|SUFFIX
madeira	madeira:ROOT|ROOT::NOMINAL
madeira's	madeira:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
man-eating	man:ROOT|ROOT::NOMINAL -:UNK eating:ROOT|ROOT::VERBAL
mane	mane:ROOT|ROOT::NOMINAL
mane's	mane:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
mantis	mantis:ROOT|ROOT::NOMINAL
mantises	mantis:ROOT|ROOT::NOMINAL es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
marsh's	marsh:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
marshiest	marsh:ROOT|ROOT::NOMINAL i:DERI|DERI::ADJ|SUFFIX est:INFL|INFL::NOUNADJ|SUFFIX
mast's	mast:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
matrix's	matrix:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
matrixes	matrix:ROOT|ROOT::NOMINAL es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
matter's	matter:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
matters	matter:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
matters	matter:ROOT|ROOT::NOMINAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
measurably	measur:ROOT|ROOT::VERBAL ab:DERI|DERI::ADJ|SUFFIX ly:DERI|DERI::ADV|SUFFIX
meetinghouse	meeting:ROOT|ROOT::VERBAL house:ROOT|ROOT::NOMINAL
meetings	meeting:ROOT|ROOT::VERBAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
meritocracies	merit:ROOT|ROOT::NOMINAL o:DERI|DERI::NOUN|SUFFIX craci:DERI|DERI::NOUN|SUFFIX es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
middle-distance	middle:ROOT|ROOT::ADJECTIVAL -:UNK dist:ROOT|ROOT::ADJECTIVAL ance:DERI|DERI::NOUN|SUFFIX
middleman's	middle:ROOT|ROOT::ADJECTIVAL man:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
mild's	mild:ROOT|ROOT::ADJECTIVAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
milder	mild:ROOT|ROOT::ADJECTIVAL er:INFL|INFL::NOUNADJ|SUFFIX
mirthfully	mirth:ROOT|ROOT::NOMINAL ful:DERI|DERI::ADJ|SUFFIX ly:DERI|DERI::ADV|SUFFIX
mizzen	mizzen:ROOT|ROOT::NOMINAL
mizzenmast	mizzen:ROOT|ROOT::NOMINAL mast:ROOT|ROOT::NOMINAL
mollycoddle	molly:ROOT|ROOT::NOMINAL coddle:ROOT|ROOT::VERBAL
mollycoddle	molly:ROOT|ROOT::NOMINAL coddle:ROOT|ROOT::VERBAL
mollycoddles	molly:ROOT|ROOT::NOMINAL coddle:ROOT|ROOT::VERBAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
mollycoddles	molly:ROOT|ROOT::NOMINAL coddle:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
momma	momma:ROOT|ROOT::NOMINAL
momma's	momma:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
money's	money:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
money-grubber	money:ROOT|ROOT::NOMINAL -:UNK grubb:ROOT|ROOT::VERBAL er:DERI|DERI::NOUN|SUFFIX
monogamous	monogam:ROOT|ROOT::NOMINAL ous:DERI|DERI::ADJ|SUFFIX
monophonic	mono:DERI|PREFIX phon:DERI|DERI::NOUN|SUFFIX ic:DERI|DERI::ADJ|SUFFIX
morale	morale:ROOT|ROOT::NOMINAL
morale's	morale:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
motor	motor:ROOT|ROOT::ADJECTIVAL
motor	motor:ROOT|ROOT::NOMINAL
motor	motor:ROOT|ROOT::NOMINAL
motor-coach	motor:ROOT|ROOT::ADJECTIVAL -:UNK coach:ROOT|ROOT::NOMINAL
motorbikes	motor:ROOT|ROOT::NOMINAL bi:DERI|PREFIX ke:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
motorize	motor:ROOT|ROOT::NOMINAL ize:DERI|DERI::VERB|SUFFIX
movers	mov:ROOT|ROOT::VERBAL er:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
movers'	mov:ROOT|ROOT::VERBAL er:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
muscovites	muscov:ROOT|ROOT::NOMINAL ite:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
muscovy	muscovy:ROOT|ROOT::NOMINAL
necklace	neck:ROOT|ROOT::NOMINAL lace:ROOT|ROOT::NOMINAL
negations	negat:ROOT|ROOT::VERBAL ion:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
negative	negat:ROOT|ROOT::VERBAL ive:DERI|DERI::ADJ|SUFFIX
negative	negat:ROOT|ROOT::VERBAL ive:DERI|DERI::ADJ|SUFFIX
negative	negat:ROOT|ROOT::VERBAL ive:DERI|DERI::ADJ|SUFFIX
nudists'	nud:ROOT|ROOT::ADJECTIVAL ist:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
numismatic	numismatic:ROOT|ROOT::ADJECTIVAL
numismatists	numismat:ROOT|ROOT::ADJECTIVAL ist:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
offstage	off:ROOT stage:ROOT|ROOT::NOMINAL
offstage	off:ROOT stage:ROOT|ROOT::NOMINAL
oiler's	oil:ROOT|ROOT::NOMINAL er:DERI|DERI::NOUN|SUFFIX 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
oilrig	oil:ROOT|ROOT::NOMINAL rig:ROOT|ROOT::VERBAL
onetime	one:ROOT time:ROOT|ROOT::NOMINAL
orates	orate:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
orating	orat:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
outback's	out:ROOT back:ROOT 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
outdistance	out:DERI|PREFIX dist:ROOT|ROOT::ADJECTIVAL ance:DERI|DERI::NOUN|SUFFIX
outer	out:ROOT er:DERI|DERI::NOUN|SUFFIX
outflow	out:ROOT|ROOT::VERBAL flow:ROOT
outskirts	out:ROOT skirts:ROOT|ROOT::NOMINAL
outstays	out:DERI|PREFIX stay:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
oval's	oval:ROOT|ROOT::ADJECTIVAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
ovals	oval:ROOT|ROOT::ADJECTIVAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
over-produce	over:DERI|PREFIX -:UNK produce:ROOT|ROOT::VERBAL
overflows	over:ROOT flow:ROOT|ROOT::VERBAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
overflows	over:ROOT flow:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
overheads'	over:ROOT head:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
overheads'	overheads:ROOT|ROOT::NOMINAL ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
overlapped	over:ROOT lapp:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
overlords	over:DERI|PREFIX lord:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
own	own:ROOT
own	own:ROOT
palatable	palat:ROOT|ROOT::NOMINAL able:DERI|DERI::ADJ|SUFFIX
palate's	palate:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
part-owner	part:ROOT|ROOT::NOMINAL -:UNK own:ROOT er:DERI|DERI::NOUN|SUFFIX
password	pass:ROOT|ROOT::VERBAL word:ROOT|ROOT::NOMINAL
past	past:ROOT|ROOT::ADJECTIVAL
past	past:ROOT|ROOT::ADJECTIVAL
past	past:ROOT
past	past:ROOT
past	past:ROOT
past's	past:ROOT|ROOT::ADJECTIVAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
pastor	pastor:ROOT|ROOT::NOMINAL
pastorals	pastor:ROOT|ROOT::NOMINAL al:DERI|DERI::ADJ|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
perfumes	per:DERI|PREFIX fume:ROOT|ROOT::VERBAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
perfumes	per:DERI|PREFIX fume:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
peri	peri:ROOT|ROOT::NOMINAL
peris	peri:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
permafrost	perma:ROOT|ROOT::ADJECTIVAL frost:ROOT|ROOT::NOMINAL
permanencies	perman:ROOT|ROOT::ADJECTIVAL enci:DERI|DERI::NOUN|SUFFIX es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
persuadable	persuad:ROOT|ROOT::VERBAL able:DERI|DERI::ADJ|SUFFIX
persuasive	per:DERI|PREFIX suas:ROOT|ROOT::NOMINAL ive:DERI|DERI::ADJ|SUFFIX
persuasive	persuas:ROOT|ROOT::VERBAL ive:DERI|DERI::ADJ|SUFFIX
persuasively	per:DERI|PREFIX suas:ROOT|ROOT::NOMINAL ive:DERI|DERI::ADJ|SUFFIX ly:DERI|DERI::ADV|SUFFIX
persuasively	persuas:ROOT|ROOT::VERBAL ive:DERI|DERI::ADJ|SUFFIX ly:DERI|DERI::ADV|SUFFIX
pilot	pilot:ROOT|ROOT::NOMINAL
pilot	pilot:ROOT|ROOT::NOMINAL
pilot	pilot:ROOT|ROOT::NOMINAL
placed	plac:ROOT|ROOT::NOMINAL ed:INFL|INFL::CONJ|SUFFIX
placed	placed:ROOT|ROOT::VERBAL
pleased	pleas:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
pleased	pleased:ROOT|ROOT::VERBAL
plectrum	plectrum:ROOT|ROOT::NOMINAL
plectrums	plectrum:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
polarize	pol:ROOT|ROOT::NOMINAL ar:DERI|DERI::NOUN|SUFFIX ize:DERI|DERI::VERB|SUFFIX
pontificate	pontific:ROOT|ROOT::NOMINAL ate:DERI|DERI::VERB|SUFFIX
pontificate	pontific:ROOT|ROOT::NOMINAL ate:DERI|DERI::VERB|SUFFIX
pontificating	pontific:ROOT|ROOT::NOMINAL at:DERI|DERI::VERB|SUFFIX ing:INFL|INFL::CONJ|SUFFIX
poofs	poof:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
poofy	poof:ROOT|ROOT::NOMINAL y:DERI|DERI::ADJ|SUFFIX
poorer	poor:ROOT|ROOT::ADJECTIVAL er:INFL|INFL::NOUNADJ|SUFFIX
poorhouses	poor:ROOT|ROOT::ADJECTIVAL house:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
popinjay	popinjay:ROOT|ROOT::NOMINAL
post-mortem	post-mortem:ROOT|ROOT::ADJECTIVAL
postmortems	postmortem:ROOT|ROOT::ADJECTIVAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
potter	pott:ROOT|ROOT::NOMINAL er:DERI|DERI::NOUN|SUFFIX
potter	potter:ROOT|ROOT::VERBAL
potter	potter:ROOT|ROOT::VERBAL
pottered	potter:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
precept	precept:ROOT|ROOT::NOMINAL
precepts	precept:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
precipitates	precipitate:ROOT|ROOT::VERBAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
precipitates	precipitate:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
precipitating	precipitat:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
predisposition	pre:DERI|PREFIX dispos:ROOT|ROOT::VERBAL ition:DERI|DERI::NOUN|SUFFIX
pretentiously	pret:ROOT|ROOT::VERBAL ent:DERI|DERI::NOUN|SUFFIX ious:DERI|DERI::NOUN|SUFFIX ly:DERI|DERI::ADV|SUFFIX
proconsul	pro:DERI|PREFIX consul:ROOT|ROOT::NOMINAL
prod	prod:ROOT|ROOT::VERBAL
prod	prod:ROOT|ROOT::VERBAL
prodded	prodd:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
produced	produc:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
professorships	profess:ROOT|ROOT::VERBAL or:DERI|DERI::NOUN|SUFFIX ship:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
proportion	proportion:ROOT|ROOT::VERBAL
proportion	proportion:ROOT|ROOT::VERBAL
protestants	protest:ROOT|ROOT::VERBAL ant:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
protestants'	protest:ROOT|ROOT::VERBAL ant:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
protractor	protract:ROOT|ROOT::VERBAL or:DERI|DERI::NOUN|SUFFIX
proviso	proviso:ROOT|ROOT::NOMINAL
provisos	proviso:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
prune	prune:ROOT|ROOT::NOMINAL
prune	prune:ROOT|ROOT::VERBAL
prunes	prune:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
prunes	prune:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
prunes'	prune:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
pupa	pupa:ROOT|ROOT::NOMINAL
pupate	pup:ROOT|ROOT::NOMINAL ate:DERI|DERI::VERB|SUFFIX
purred	purr:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
purring	purr:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
put-ons	put:ROOT|ROOT::VERBAL -:UNK on:ROOT s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
putrefied	putrefi:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
putrefy	putrefy:ROOT|ROOT::VERBAL
puts	put:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
puts	put:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
radioactivity	radio:DERI|PREFIX act:ROOT|ROOT::VERBAL iv:DERI|DERI::ADJ|SUFFIX ity:DERI|DERI::NOUN|SUFFIX
radiotherapist	radio:DERI|PREFIX therap:ROOT|ROOT::NOMINAL ist:DERI|DERI::NOUN|SUFFIX
rampant	ramp:ROOT|ROOT::VERBAL ant:DERI|DERI::NOUN|SUFFIX
rat-a-tat-tat	rat-a-tat-tat:ROOT|ROOT::NOMINAL
reappearance	re:DERI|PREFIX appear:ROOT|ROOT::VERBAL ance:DERI|DERI::NOUN|SUFFIX
recapitulated	re:DERI|PREFIX capitulat:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
redcaps	red:ROOT|ROOT::ADJECTIVAL cap:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
reduce	reduce:ROOT|ROOT::VERBAL
reducing	reduc:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
refracted	refract:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
refracts	refract:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
regression	regress:ROOT|ROOT::VERBAL ion:DERI|DERI::NOUN|SUFFIX
regressive	regress:ROOT|ROOT::VERBAL ive:DERI|DERI::ADJ|SUFFIX
regulations	regulat:ROOT|ROOT::VERBAL ion:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
regulators	regulat:ROOT|ROOT::VERBAL or:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
regulators'	regulat:ROOT|ROOT::VERBAL or:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
rein's	rein:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
reins'	rein:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
reins'	reins:ROOT|ROOT::NOMINAL ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
rejuvenation	re:DERI|PREFIX juven:ROOT|ROOT::ADJECTIVAL at:DERI|DERI::VERB|SUFFIX ion:DERI|DERI::NOUN|SUFFIX
remorseful	remorse:ROOT|ROOT::NOMINAL ful:DERI|DERI::ADJ|SUFFIX
remorsefully	remorse:ROOT|ROOT::NOMINAL ful:DERI|DERI::ADJ|SUFFIX ly:DERI|DERI::ADV|SUFFIX
remunerate	remunerate:ROOT|ROOT::VERBAL
remunerated	remunerat:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
repressiveness	re:DERI|PREFIX press:ROOT|ROOT::VERBAL ive:DERI|DERI::ADJ|SUFFIX ness:DERI|DERI::NOUN|SUFFIX
researchers	re:DERI|PREFIX search:ROOT|ROOT::VERBAL er:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
reseat	re:DERI|PREFIX seat:ROOT|ROOT::NOMINAL
reunion's	re:DERI|PREFIX un:ROOT|ROOT::VERBAL ion:DERI|DERI::NOUN|SUFFIX 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
reunion's	re:DERI|PREFIX union:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
rigger	rigg:ROOT|ROOT::VERBAL er:DERI|DERI::NOUN|SUFFIX
right	right:ROOT|ROOT::VERBAL
right	right:ROOT|ROOT::VERBAL
right	right:ROOT|ROOT::VERBAL
right	right:ROOT|ROOT::VERBAL
right-handed	right:ROOT|ROOT::VERBAL -:UNK hand:ROOT|ROOT::NOMINAL ed:DERI|DERI::ADJ|SUFFIX
rocker's	rock:ROOT|ROOT::VERBAL er:DERI|DERI::NOUN|SUFFIX 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
rockiness	rock:ROOT|ROOT::NOMINAL i:DERI|DERI::ADJ|SUFFIX ness:DERI|DERI::NOUN|SUFFIX
rocks	rock:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
rocks	rock:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
rocks	rocks:ROOT|ROOT::NOMINAL
rococo	rococo:ROOT|ROOT::ADJECTIVAL
rollick	rollick:ROOT|ROOT::VERBAL
rollicked	rollick:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
romantic's	romant:ROOT|ROOT::NOMINAL ic:DERI|DERI::ADJ|SUFFIX 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
romanticists	romant:ROOT|ROOT::NOMINAL ic:DERI|DERI::ADJ|SUFFIX ist:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
roundabouts	round:ROOT|ROOT::ADJECTIVAL about:ROOT s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
roundsman	round:ROOT|ROOT::ADJECTIVAL s:UNK man:ROOT|ROOT::NOMINAL
roundup	round:ROOT|ROOT::ADJECTIVAL up:ROOT
rowanberry	rowan:ROOT|ROOT::NOMINAL berry:ROOT|ROOT::NOMINAL
rowdies	rowdi:ROOT|ROOT::ADJECTIVAL es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
rowdiness	rowdi:ROOT|ROOT::ADJECTIVAL ness:DERI|DERI::NOUN|SUFFIX
sacristan	sacrist:ROOT|ROOT::NOMINAL an:DERI|DERI::ADJ|SUFFIX
sacristans	sacrist:ROOT|ROOT::NOMINAL an:DERI|DERI::ADJ|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
salt's	salt:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
saltiness	salt:ROOT|ROOT::NOMINAL i:DERI|DERI::ADJ|SUFFIX ness:DERI|DERI::NOUN|SUFFIX
sandalwood	sandal:ROOT|ROOT::NOMINAL wood:ROOT|ROOT::NOMINAL
sang	sang:ROOT|ROOT::VERBAL
saxophone	sax:ROOT|ROOT::NOMINAL o:DERI|DERI::NOUN|SUFFIX phone:DERI|DERI::NOUN|SUFFIX
saxophonist	sax:ROOT|ROOT::NOMINAL o:DERI|DERI::NOUN|SUFFIX phon:DERI|DERI::NOUN|SUFFIX ist:DERI|DERI::NOUN|SUFFIX
scoreboard's	score:ROOT board:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
scorecards	score:ROOT card:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
scorer's	scor:ROOT|ROOT::NOMINAL er:DERI|DERI::NOUN|SUFFIX 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
scribble	scribble:ROOT|ROOT::VERBAL
scribble	scribble:ROOT|ROOT::VERBAL
scribbling	scribbl:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
searched	search:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
sensitive	sensitive:ROOT|ROOT::ADJECTIVAL
serpentine	serpent:ROOT|ROOT::NOMINAL ine:DERI|DERI::VERB|SUFFIX
serpents'	serpent:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
settle	settle:ROOT|ROOT::NOMINAL
settle	settle:ROOT|ROOT::NOMINAL
settler's	settl:ROOT|ROOT::NOMINAL er:DERI|DERI::NOUN|SUFFIX 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
seventeen's	seven:ROOT teen:UNK 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
shantytown	shanty:ROOT|ROOT::NOMINAL town:ROOT|ROOT::NOMINAL
shay's	shay:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
shays'	shay:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
sheer	sheer:ROOT|ROOT::ADJECTIVAL
sheer	sheer:ROOT|ROOT::ADJECTIVAL
sheer	sheer:ROOT|ROOT::VERBAL
sheered	sheer:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
shenanigan	shenanigan:ROOT|ROOT::NOMINAL
shenanigans	shenanigan:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
shogun	shogun:ROOT|ROOT::NOMINAL
shogun's	shogun:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
showbiz	show:ROOT|ROOT::VERBAL biz:ROOT|ROOT::ADJECTIVAL
showmanship's	show:ROOT|ROOT::VERBAL man:ROOT|ROOT::NOMINAL ship:DERI|DERI::NOUN|SUFFIX 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
sicilian's	sicili:ROOT|ROOT::NOMINAL an:DERI|DERI::ADJ|SUFFIX 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
sicilians	sicili:ROOT|ROOT::NOMINAL an:DERI|DERI::ADJ|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
similarly	similar:ROOT|ROOT::ADJECTIVAL ly:DERI|DERI::ADV|SUFFIX
singers	sing:ROOT|ROOT::VERBAL er:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
sinking-fund	sinking:ROOT|ROOT::VERBAL -:UNK fund:ROOT|ROOT::NOMINAL
sip	sip:ROOT|ROOT::VERBAL
sip	sip:ROOT|ROOT::VERBAL
sip's	sip:ROOT|ROOT::VERBAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
sips	sip:ROOT|ROOT::VERBAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
sips	sip:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
sixthly	six:ROOT th:INFL|INFL::NOUNADJ|SUFFIX ly:DERI|DERI::ADV|SUFFIX
skirl	skirl:ROOT|ROOT::NOMINAL
smooch	smooch:ROOT|ROOT::VERBAL
smooch	smooch:ROOT|ROOT::VERBAL
smooched	smooch:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
smoother	smooth:ROOT|ROOT::ADJECTIVAL er:INFL|INFL::NOUNADJ|SUFFIX
snap	snap:UNK
snap	snap:ROOT|ROOT::VERBAL
snap	snap:ROOT|ROOT::VERBAL
snap	snap:ROOT|ROOT::VERBAL
snappishly	snapp:ROOT|ROOT::VERBAL ish:DERI|DERI::ADJ|SUFFIX ly:DERI|DERI::ADV|SUFFIX
snob's	snob:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
snobs'	snob:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
soda-fountain	soda:ROOT|ROOT::NOMINAL -:UNK fountain:ROOT|ROOT::NOMINAL
sodium	sod:ROOT|ROOT::NOMINAL ium:DERI|DERI::NOUN|SUFFIX
soft-pedalled	soft:ROOT|ROOT::ADJECTIVAL -:UNK pedall:ROOT|ROOT::NOMINAL ed:INFL|INFL::CONJ|SUFFIX
spaceships	space:ROOT|ROOT::NOMINAL ship:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
spasmodic	spasmod:ROOT|ROOT::NOMINAL ic:DERI|DERI::ADJ|SUFFIX
spastics'	spast:ROOT|ROOT::NOMINAL ic:DERI|DERI::ADJ|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
sped	sped:ROOT|ROOT::VERBAL
speeded	speed:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
stagecoach's	stage:ROOT|ROOT::NOMINAL coach:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
standardizes	standard:ROOT|ROOT::ADJECTIVAL ize:DERI|DERI::VERB|SUFFIX s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
standbys	stand:ROOT|ROOT::VERBAL by:ROOT s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
stayers	stay:ROOT|ROOT::VERBAL er:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
stirred	stirr:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
stodgy	stodg:ROOT|ROOT::NOMINAL y:DERI|DERI::ADJ|SUFFIX
strafed	straf:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
strafes	strafe:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
streak	streak:ROOT|ROOT::VERBAL
streak	streak:ROOT|ROOT::VERBAL
streakers	streak:ROOT|ROOT::VERBAL er:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
stringing	string:ROOT|ROOT::NOMINAL ing:INFL|INFL::CONJ|SUFFIX
strung	strung:ROOT|ROOT::NOMINAL
strung	strung:ROOT|ROOT::VERBAL
substandard	sub:DERI|PREFIX standard:ROOT|ROOT::ADJECTIVAL
substantiate	substanti:ROOT|ROOT::NOMINAL ate:DERI|DERI::VERB|SUFFIX
sucrose	sucrose:ROOT|ROOT::NOMINAL
suffuse	suffuse:ROOT|ROOT::VERBAL
suffuses	suffuse:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
supposed	suppos:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
supposed	supposed:ROOT|ROOT::VERBAL
supposedly	supposed:ROOT|ROOT::VERBAL ly:DERI|DERI::ADV|SUFFIX
survivor's	surviv:ROOT|ROOT::VERBAL or:DERI|DERI::NOUN|SUFFIX 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
survivors'	surviv:ROOT|ROOT::VERBAL or:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
suture	suture:ROOT|ROOT::NOMINAL
suture's	suture:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
swede	swede:ROOT|ROOT::NOMINAL
swede	swede:ROOT|ROOT::NOMINAL
swedes	swede:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
swedes	swede:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
sybaritic	sybar:ROOT|ROOT::NOMINAL it:DERI|DERI::NOUN|SUFFIX ic:DERI|DERI::ADJ|SUFFIX
symbolically	symbol:ROOT|ROOT::NOMINAL ic:DERI|DERI::ADJ|SUFFIX ally:DERI|DERI::ADV|SUFFIX
symbolically	symbol:ROOT|ROOT::NOMINAL ical:DERI|DERI::ADJ|SUFFIX ly:DERI|DERI::ADV|SUFFIX
symbolization	symbol:ROOT|ROOT::NOMINAL iz:DERI|DERI::VERB|SUFFIX ation:DERI|DERI::NOUN|SUFFIX
talking-points	talking:ROOT|ROOT::VERBAL -:UNK point:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
tangle	tangle:ROOT|ROOT::VERBAL
tangle	tangle:ROOT|ROOT::VERBAL
tape-measure	tape:ROOT|ROOT::NOMINAL -:UNK measure:ROOT|ROOT::VERBAL
tartaric	tartar:ROOT|ROOT::NOMINAL ic:DERI|DERI::ADJ|SUFFIX
tartars'	tartar:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
tasteless	taste:ROOT|ROOT::VERBAL less:DERI|DERI::ADJ|SUFFIX
test-drives	test:ROOT|ROOT::NOMINAL -:UNK drive:ROOT|ROOT::VERBAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
test-drives	test:ROOT|ROOT::NOMINAL -:UNK drive:ROOT|ROOT::VERBAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
testers	test:ROOT|ROOT::NOMINAL er:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
therapies	therapi:ROOT|ROOT::NOMINAL es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
timbre	timbre:ROOT|ROOT::NOMINAL
timbres	timbre:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
time-limits	time:ROOT|ROOT::NOMINAL -:UNK limit:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
toe	toe:ROOT|ROOT::NOMINAL
toe	toe:ROOT|ROOT::NOMINAL
toe-cap	toe:ROOT|ROOT::NOMINAL -:UNK cap:ROOT|ROOT::NOMINAL
tollgate	toll:ROOT|ROOT::VERBAL gate:ROOT|ROOT::NOMINAL
tollgates	toll:ROOT|ROOT::VERBAL gate:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
toted	tot:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
totem-pole	totem:ROOT|ROOT::NOMINAL -:UNK pole:ROOT|ROOT::NOMINAL
totem-poles	totem:ROOT|ROOT::NOMINAL -:UNK pole:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
toting	tot:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
townswomen	town:ROOT|ROOT::NOMINAL s:UNK women:ROOT|ROOT::NOMINAL
trainable	train:ROOT|ROOT::VERBAL able:DERI|DERI::ADJ|SUFFIX
training	train:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
training	training:ROOT|ROOT::VERBAL
training's	training:ROOT|ROOT::VERBAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
transient	transient:ROOT|ROOT::ADJECTIVAL
transient	transient:ROOT|ROOT::ADJECTIVAL
transients	transient:ROOT|ROOT::ADJECTIVAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
treatable	treat:ROOT|ROOT::VERBAL able:DERI|DERI::ADJ|SUFFIX
trespass	trespass:ROOT|ROOT::VERBAL
trespass	trespass:ROOT|ROOT::VERBAL
trespasser	trespass:ROOT|ROOT::VERBAL er:DERI|DERI::NOUN|SUFFIX
trike	tri:DERI|PREFIX ke:ROOT|ROOT::NOMINAL
tripartite	tri:DERI|PREFIX part:ROOT|ROOT::NOMINAL ite:DERI|DERI::NOUN|SUFFIX
triviality	trivial:ROOT|ROOT::ADJECTIVAL ity:DERI|DERI::NOUN|SUFFIX
trivialized	trivial:ROOT|ROOT::ADJECTIVAL iz:DERI|DERI::VERB|SUFFIX ed:INFL|INFL::CONJ|SUFFIX
try-out	try:ROOT|ROOT::VERBAL -:UNK out:ROOT
trying	try:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
trying	trying:ROOT|ROOT::VERBAL
turning	turn:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
turning	turning:ROOT|ROOT::VERBAL
turning-points	turning:ROOT|ROOT::VERBAL -:UNK point:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
tusk's	tusk:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
tusks	tusk:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
tut	tut:UNK
tut	tut:UNK
tutting	tutt:UNK ing:INFL|INFL::CONJ|SUFFIX
twentieth's	twentie:ROOT th:INFL|INFL::NOUNADJ|SUFFIX 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
twenty-one's	twenty:ROOT -:UNK one:ROOT 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
under	under:ROOT
under	under:ROOT
undergrad	under:ROOT grad:ROOT|ROOT::VERBAL
underscore	under:ROOT score:ROOT|ROOT::NOMINAL
undertaker's	under:ROOT tak:ROOT|ROOT::VERBAL er:DERI|DERI::NOUN|SUFFIX 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
undertakers'	under:ROOT tak:ROOT|ROOT::VERBAL er:DERI|DERI::NOUN|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
undone	un:DERI|PREFIX done:ROOT|ROOT::VERBAL
undone	un:DERI|PREFIX done:ROOT|ROOT::VERBAL
undone	undone:ROOT|ROOT::VERBAL
uneconomical	un:DERI|PREFIX ec:DERI|PREFIX onom:DERI|DERI::NOUN|SUFFIX ical:DERI|DERI::ADJ|SUFFIX
unofficially	un:DERI|PREFIX offic:ROOT|ROOT::NOMINAL ial:DERI|DERI::ADJ|SUFFIX ly:DERI|DERI::ADV|SUFFIX
unplaced	un:DERI|PREFIX placed:ROOT|ROOT::VERBAL
unprofessionally	un:DERI|PREFIX profess:ROOT|ROOT::VERBAL ion:DERI|DERI::NOUN|SUFFIX al:DERI|DERI::ADJ|SUFFIX ly:DERI|DERI::ADV|SUFFIX
unseats	un:DERI|PREFIX seat:ROOT|ROOT::NOMINAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
unseemliness	un:DERI|PREFIX seem:ROOT|ROOT::VERBAL li:DERI|DERI::ADV|SUFFIX ness:DERI|DERI::NOUN|SUFFIX
unseemly	un:DERI|PREFIX seem:ROOT|ROOT::VERBAL ly:DERI|DERI::ADV|SUFFIX
untangling	un:DERI|PREFIX tangl:ROOT|ROOT::VERBAL ing:INFL|INFL::CONJ|SUFFIX
vanquished	vanquish:ROOT|ROOT::VERBAL ed:INFL|INFL::CONJ|SUFFIX
vanquishes	vanquish:ROOT|ROOT::VERBAL es:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
vast	vast:ROOT|ROOT::ADJECTIVAL
vastly	vast:ROOT|ROOT::ADJECTIVAL ly:DERI|DERI::ADV|SUFFIX
venezuela	venezuela:ROOT|ROOT::NOMINAL
venezuelans	venezuel:ROOT|ROOT::NOMINAL an:DERI|DERI::ADJ|SUFFIX s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
victories	vict:ROOT|ROOT::NOMINAL ori:DERI|DERI::ADJ|DERI::NOUN|SUFFIX es:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
victors'	victor:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
videotape	video:ROOT|ROOT::ADJECTIVAL tape:ROOT|ROOT::NOMINAL
videotape	video:ROOT|ROOT::ADJECTIVAL tape:ROOT|ROOT::NOMINAL
vileness	vile:ROOT|ROOT::ADJECTIVAL ness:DERI|DERI::NOUN|SUFFIX
vilified	vil:ROOT|ROOT::ADJECTIVAL ifi:DERI|DERI::VERB|SUFFIX ed:INFL|INFL::CONJ|SUFFIX
visa	visa:ROOT|ROOT::NOMINAL
visa	visa:ROOT|ROOT::NOMINAL
visas	visa:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
visas	visa:ROOT|ROOT::NOMINAL s:INFL|INFL::CONJ|INFL::CONJ::NUMBER|INFL::CONJ::PERSON|SUFFIX
waken	wak:ROOT|ROOT::VERBAL en:DERI|DERI::ADJ|SUFFIX
warehouses'	ware:ROOT|ROOT::NOMINAL house:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
warily	wari:ROOT|ROOT::ADJECTIVAL ly:DERI|DERI::ADV|SUFFIX
warlike	war:ROOT|ROOT::NOMINAL like:DERI|DERI::ADJ|SUFFIX
warm-hearted	warm:ROOT|ROOT::ADJECTIVAL -:UNK heart:ROOT|ROOT::NOMINAL ed:DERI|DERI::ADJ|SUFFIX
warmer	warm:ROOT|ROOT::ADJECTIVAL er:INFL|INFL::NOUNADJ|SUFFIX
warmer	warm:ROOT|ROOT::ADJECTIVAL er:DERI|DERI::NOUN|SUFFIX
wary	wary:ROOT|ROOT::ADJECTIVAL
washerwoman	wash:ROOT|ROOT::VERBAL er:DERI|DERI::NOUN|SUFFIX woman:ROOT|ROOT::NOMINAL
wearied	weari:ROOT|ROOT::ADJECTIVAL ed:INFL|INFL::CONJ|SUFFIX
wedged	wedg:ROOT|ROOT::NOMINAL ed:INFL|INFL::CONJ|SUFFIX
wedged	wedged:ROOT|ROOT::VERBAL
wedging	wedg:ROOT|ROOT::NOMINAL ing:INFL|INFL::CONJ|SUFFIX
whitecaps	white:ROOT|ROOT::ADJECTIVAL cap:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
wood's	wood:ROOT|ROOT::NOMINAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
work's	work:ROOT|ROOT::VERBAL 's:INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
workbooks	work:ROOT|ROOT::VERBAL book:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
workhorse	work:ROOT|ROOT::VERBAL horse:ROOT|ROOT::NOMINAL
workmanlike	work:ROOT|ROOT::VERBAL man:ROOT|ROOT::NOMINAL like:DERI|DERI::ADJ|SUFFIX
workshop	work:ROOT|ROOT::VERBAL shop:ROOT|ROOT::NOMINAL
world-weary	world:ROOT|ROOT::NOMINAL -:UNK weary:ROOT|ROOT::ADJECTIVAL
worse	worse:ROOT|ROOT::ADJECTIVAL
worse	worse:ROOT|ROOT::ADJECTIVAL
worse	worse:ROOT|ROOT::ADJECTIVAL
worse	worse:ROOT|ROOT::ADJECTIVAL
worsened	wors:ROOT|ROOT::ADJECTIVAL en:DERI|DERI::ADJ|SUFFIX ed:INFL|INFL::CONJ|SUFFIX
yearbooks	year:ROOT|ROOT::NOMINAL book:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
years	year:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX
years	years:ROOT|ROOT::NOMINAL
years'	year:ROOT|ROOT::NOMINAL s:INFL|INFL::NOUNADJ|INFL::NOUNADJ::NUMBER|SUFFIX ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
years'	years:ROOT|ROOT::NOMINAL ':INFL|INFL::NOUNADJ|INFL::NOUNADJ::CASE|SUFFIX
yeast	yeast:ROOT|ROOT::NOMINAL
yeasty	yeast:ROOT|ROOT::NOMINAL y:DERI|DERI::ADJ|SUFFIX
