.TH fst-parse2 1 "October 2003" "" "fst-parse2"
.SH NAME
fst-parse2 \- analyses input with a pipeline of transducers
.SH SYNOPSIS
.B fst-parse2
.I file1 [ file [ file ] ]
.SH OPTIONS
.TP
.B \-t file
add the transducer stored in 
.I file
at the end of the pipeline.
.TP
.B \-h
print usage information.
.TP
.B \-q
quiet mode
.TP
.B \-d
debugging mode
.SH DESCRIPTION
.I fst-parse2
is similar to 
.I fst-parse
but prints the transducer resulting from the composition of the input
string with the argument transducer(s) instead of a sequence of
analysis strings.

.SH BUGS
No bugs are known so far.
.SH "SEE ALSO"
fst-parse
.SH AUTHOR
Helmut Schmid,
Institute for Computational Linguistics,
University of Stuttgart,
Email: schmid@ims.uni-stuttgart.de,
This software is available under the GNU Public License.
