.TH fst-compact 1 "October 2004" "" "fst-compact"
.SH NAME
fst-compact \- transforms transducers to the compact format
.SH SYNOPSIS
.B fst-compact
.I [ file [ file ] ]
.SH DESCRIPTION
.I fst-compact
reads a transducer in standard format from the input and writes it in
compact format to the output. The compact format is required by 
.I fst-infl2.

.SH BUGS
No bugs are known so far.
.SH "SEE ALSO"
fst-compiler, fst-infl3
.SH AUTHOR
Helmut Schmid,
Institute for Computational Linguistics,
University of Stuttgart,
Email: schmid@ims.uni-stuttgart.de,
This software is available under the GNU Public License.
