.TH fst-compare 1 "February 2002" "" "fst-compare"
.SH NAME
fst-compare \- checks whether two transducers are equivalent
.SH SYNOPSIS
.B fst-compare
.I file1 file2
.SH DESCRIPTION
.I fst-compare
checks whether the two transducers stored in
.I file1
and
.I file2
are equivalent.

.SH BUGS
No bugs are known so far.
.SH "SEE ALSO"
fst-compiler
.SH AUTHOR
Helmut Schmid,
Institute for Computational Linguistics,
University of Stuttgart,
Email: schmid@ims.uni-stuttgart.de,
This software is available under the GNU Public License.
